# Usa una imagen ligera de Nginx
FROM nginx:alpine

# Copia todos los archivos del frontend al directorio web de Nginx
COPY . /usr/share/nginx/html

# Expone el puerto 80
EXPOSE 80

# Nginx ya corre automáticamente, así que no necesitas CMD
